# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='name',
            field=models.CharField(default='DummyObject', max_length=120),
        ),
    ]
